project_root: .
task1:
  object_a:
    raw_input: data/raw/object_A
    colmap_dataset: data/task1/object_A_colmap
    model_dir: results/task1/2dgs/object_A_rgba_cropped_alpha_clean
    mesh_path: results/task1/2dgs/object_A_rgba_cropped_alpha_clean/train/ours_latest/fuse_post_2dgs_tsdf_main_component.ply
  object_b:
    prompt: "a small toy car, smooth colorful plastic, simple rounded shape, single object, centered"
    model_dir: results/task1/aigc/object_B_text3d
    mesh_path: results/task1/aigc/object_B_text3d/export/model.obj
  object_c:
    input_image: data/raw/object_C/object_c.png
    prompt: "a cute rabbit doll toy with a purple bow, full body, 3D object"
    model_dir: results/task1/aigc/object_C_image3d
    mesh_path: results/task1/aigc/object_C_image3d/model.obj
  background:
    scene: garden
    dataset: data/task1/mipnerf360_full/garden
    model_dir: results/task1/2dgs/background_garden_full
    mesh_path: results/task1/2dgs/background_garden_full/train/ours_latest/fuse_unbounded_post_crop_q02_98.ply
    final_mesh_fusion_background: results/task1/fusion_mesh/garden_scene_upright_topopen_q05.ply
  training:
    iterations: 30000
    object_resolution: 2
    background_resolution: 4
    lambda_normal: 0.05
    lambda_distortion: 100.0
  fusion:
    blender_config: configs/fusion_mesh_table.json
    renderer: scripts/task1/render_mesh_table_fusion.py
    output_dir: results/task1/fusion_mesh
